# Generated by Django 4.0.4 on 2022-05-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_bio_user_birthday_user_email_user_joindate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='joindate',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
