# Generated by Django 4.0.4 on 2022-05-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_birthday_alter_user_joindate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profileimg',
            field=models.TextField(blank=True, max_length=9999, null=True),
        ),
    ]
