# Generated by Django 4.0.4 on 2022-05-06 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_itemforsale_seller_alter_offer_buyer'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0004_alter_user_profileimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profileimg', models.TextField(blank=True, max_length=9999, null=True)),
                ('bio', models.TextField(default=None, max_length=9999)),
                ('birthday', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
