# Generated by Django 4.0.4 on 2022-05-06 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0005_user_info_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address_info',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('street_name', models.CharField(default=None, max_length=255)),
                ('zip', models.IntegerField(default=None)),
                ('city', models.CharField(default=None, max_length=255)),
                ('country', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_info',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('card_nr', models.IntegerField(default=None)),
                ('expires', models.CharField(default=None, max_length=5)),
                ('cvc', models.IntegerField(default=None)),
            ],
        ),
        migrations.AlterField(
            model_name='user_info',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
