# Generated by Django 4.0.4 on 2022-05-06 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0006_address_info_payment_info_alter_user_info_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_rating',
            fields=[
                ('userid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_rating', models.IntegerField(default=None)),
            ],
        ),
    ]
