# Generated by Django 4.0.4 on 2022-05-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address_info',
            name='zip',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
