# Generated by Django 4.0.4 on 2022-05-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_payment_info_card_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_info',
            name='card_nr',
            field=models.IntegerField(default=None, max_length=20),
        ),
    ]
