# Generated by Django 4.0.4 on 2022-05-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_payment_info_card_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_rating',
            name='user_rating',
            field=models.BigIntegerField(default=None),
        ),
    ]
