# Generated by Django 4.0.4 on 2022-05-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_rating_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_info',
            name='card_nr',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='user_rating',
            name='user_rating',
            field=models.IntegerField(default=None),
        ),
    ]
