# Generated by Django 4.0.4 on 2022-05-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_payment_info_card_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_info',
            name='expires',
            field=models.DateField(default=None, max_length=5),
        ),
    ]
