# Generated by Django 4.0.4 on 2022-05-10 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_alter_offer_approved_alter_offer_buyer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0017_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.offer'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
