# Generated by Django 4.0.4 on 2022-05-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_notification_offer_notification_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
