# Generated by Django 4.0.4 on 2022-05-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_notification_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='bio',
            field=models.TextField(blank=True, default=None, max_length=9999, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='birthday',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='profileimg',
            field=models.TextField(blank=True, default=None, max_length=9999, null=True),
        ),
    ]
