# Generated by Django 4.0.4 on 2022-05-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_notification_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='birthday',
            field=models.DateField(default=None),
        ),
    ]
