# Generated by Django 4.0.4 on 2022-05-11 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_user_info_bio_alter_user_info_birthday_and_more'),
        ('users', '0020_alter_user_info_birthday'),
    ]

    operations = [
    ]
