# Generated by Django 4.0.4 on 2022-05-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_merge_20220511_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_info',
            name='expires',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
