# Generated by Django 4.0.4 on 2022-05-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_merge_20220511_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='profileimg',
            field=models.TextField(blank=True, default='profile-icon.png', max_length=9999, null=True),
        ),
    ]
