# Generated by Django 4.0.4 on 2022-05-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_user_info_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='profileimg',
            field=models.ImageField(blank=True, default='profile-icon.png', null=True, upload_to=''),
        ),
    ]
