# Generated by Django 4.0.4 on 2022-05-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_payment_info_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_info',
            name='card_nr',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='payment_info',
            name='cvc',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='payment_info',
            name='expires',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
