# Generated by Django 4.0.4 on 2022-05-12 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_user_info_profileimg'),
        ('users', '0025_alter_payment_info_card_nr_alter_payment_info_cvc_and_more'),
    ]

    operations = [
    ]
