# Generated by Django 4.0.4 on 2022-05-12 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ItemForSale',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_of_upload', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('condition', models.CharField(max_length=50)),
                ('min_bid', models.IntegerField()),
                ('cur_bid', models.IntegerField(blank=True, default=0)),
                ('sold', models.BooleanField(default=False)),
                ('long_desc', models.TextField(max_length=400)),
                ('seller', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time_of_offer', models.DateTimeField(blank=True)),
                ('price', models.IntegerField()),
                ('approved', models.BooleanField(blank=True, default=None)),
                ('buyer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='items.itemforsale')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.category')),
            ],
        ),
        migrations.CreateModel(
            name='SoldItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items.itemforsale')),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items.offer')),
            ],
        ),
        migrations.CreateModel(
            name='ItemImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='favicon-fyresale.svg', null=True, upload_to='')),
                ('main_image', models.BooleanField(blank=True, default=None)),
                ('item', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='items.itemforsale')),
            ],
        ),
        migrations.AddField(
            model_name='itemforsale',
            name='sub_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.subcategory'),
        ),
    ]
