# Generated by Django 4.0.4 on 2022-05-03 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ItemForSale',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.TextField(max_length=9999)),
                ('time_of_upload', models.DateTimeField()),
                ('min_bid', models.FloatField()),
                ('cur_bid', models.FloatField()),
                ('sold', models.BooleanField()),
                ('long_desc', models.TextField(max_length=9999)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time_of_offer', models.DateTimeField()),
                ('price', models.FloatField()),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemforsale')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.category')),
            ],
        ),
        migrations.CreateModel(
            name='SoldItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemforsale')),
                ('offer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.offer')),
            ],
        ),
        migrations.AddField(
            model_name='itemforsale',
            name='sub_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.subcategory'),
        ),
    ]
