# Generated by Django 4.0.4 on 2022-05-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimages',
            name='main_image',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
