# Generated by Django 4.0.4 on 2022-05-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='itemimages',
            name='main_image',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='itemforsale',
            name='condition',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='itemforsale',
            name='long_desc',
            field=models.TextField(max_length=400),
        ),
    ]
