# Generated by Django 4.0.4 on 2022-05-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemforsale',
            name='condition',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemforsale',
            name='image',
            field=models.TextField(blank=True, max_length=9999, null=True),
        ),
        migrations.AlterField(
            model_name='itemforsale',
            name='time_of_upload',
            field=models.CharField(max_length=255),
        ),
    ]
