# Generated by Django 4.0.4 on 2022-05-12 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_category_image_itemimages_main_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solditem',
            old_name='itemid',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='solditem',
            old_name='offerid',
            new_name='offer',
        ),
    ]
