# Generated by Django 4.0.4 on 2022-05-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_category_image_itemimages_main_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimages',
            name='main_image',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
