# Generated by Django 4.0.4 on 2022-05-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_itemforsale_condition_alter_itemforsale_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.TextField(blank=True, max_length=9999, null=True),
        ),
    ]
