# Generated by Django 4.0.4 on 2022-05-12 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_itemimages_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemforsale',
            name='image',
        ),
    ]
