# Generated by Django 4.0.4 on 2022-05-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemforsale',
            old_name='seller_id',
            new_name='seller',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='buyer_id',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='solditem',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='solditem',
            old_name='offer_id',
            new_name='offer',
        ),
        migrations.AddField(
            model_name='itemforsale',
            name='date_of_upload',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
