# Generated by Django 4.0.4 on 2022-05-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_rename_seller_id_itemforsale_seller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemforsale',
            name='cur_bid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='itemforsale',
            name='min_bid',
            field=models.IntegerField(),
        ),
    ]
