# Generated by Django 4.0.4 on 2022-05-06 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_info_delete_user'),
        ('items', '0007_alter_itemforsale_seller_alter_offer_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solditem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='solditem',
            name='offer',
        ),
        migrations.AddField(
            model_name='offer',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solditem',
            name='itemid',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='items.itemforsale'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solditem',
            name='offerid',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='items.offer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user_info'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.IntegerField(),
        ),
    ]
