# Generated by Django 4.0.4 on 2022-05-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_remove_solditem_item_remove_solditem_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemforsale',
            name='image',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
