# Generated by Django 4.0.4 on 2022-05-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_alter_itemforsale_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemforsale',
            name='image',
            field=models.CharField(max_length=9999),
        ),
    ]
