# Generated by Django 4.0.4 on 2022-05-09 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0011_alter_offer_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemforsale',
            name='cur_bid',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='itemforsale',
            name='date_of_upload',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='itemforsale',
            name='seller',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemforsale',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itemforsale',
            name='time_of_upload',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
