# Generated by Django 4.0.4 on 2022-05-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_alter_offer_approved_alter_offer_buyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemforsale',
            name='image',
            field=models.ImageField(blank=True, default='photo.png', null=True, upload_to=''),
        ),
    ]
