# Generated by Django 4.0.4 on 2022-05-12 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_alter_itemforsale_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemforsale',
            name='time_of_upload',
        ),
    ]
